### ISSUE TITLE
insufficient spacing to the right of letters

### ISSUE THREAD

**Issue by amkhlv** [opencollab/jlatexmath#10]
for example, when I need $(TY)$ I have to type $(T\\,Y\\,)$ because otherwise T hits Y and Y hits )

**Comment by murkle** [comment]
Please post a screenshot showing the problem

**Comment by amkhlv** [comment]
[http://andreimikhailov.com/jlatexmath/](http://andreimikhailov.com/jlatexmath/)

**Comment by murkle** [comment]
So you mean when converting to SVG? (important detail missing from your bug report!)
andreimikhailov.com/jlatexmath/1.svg

Try exporting to SVG using FreeHEP, that works nicely for me with JLaTeXMath

**Comment by amkhlv** [comment]
I create `TeXIcon` from `TeXFormula` using `JLaTeXMath`, and then `paintIcon` it on `org.apache.batik.svggen.SVGGraphics2D`

**Comment by murkle** [comment]
Output using JLaTeXMath + FreeHEP, looks fine:
[TY.zip](https://github.com/opencollab/jlatexmath/files/966362/TY.zip)

Why do you think it's a bug in JLaTeXMath and not org.apache.batik.svggen.SVGGraphics2D?

Have you tried with FreeHEP?

**Comment by amkhlv** [comment]
may I ask you to send to me an example of your code, how do you convert using FreeHEP?

**Comment by murkle** [comment]
Try something like this:

    UserProperties props = (UserProperties) SVGGraphics2D
				.getDefaultProperties();
    props.setProperty(SVGGraphics2D.EMBED_FONTS, !textAsShapes);
    props.setProperty(AbstractVectorGraphicsIO.TEXT_AS_SHAPES,
				textAsShapes);
    SVGGraphics2D.setDefaultProperties(props);
    SVGGraphics2D g2 = new SVGGraphics2D(file,
					new Dimension((int) (pixelWidth / exportScale),
							(int) (pixelHeight / exportScale)));
    // draw to g2 as usual (SVGGraphics2D extends Graphics2D)
    g2.endExport();

**Comment by amkhlv** [comment]
So far only getting `NullPointerException` with FreeHEP. But, anyway, there is something wrong with the sample you attached in `TY.zip`. The mathematical symbols in a formula should be slanted (slightly inclined to the right). Yours are straight (vertical). Could you make them slanted? I suspect that this is where the problem is!

**Comment by amkhlv** [comment]
Update: I was able to make `FreeHEP` work, but still having the same problem. In other words, switching from `Batik` to `FreeHEP` did not resolve the issue. My working FreeHEP code [is here](https://github.com/amkhlv/latex2svg/blob/master/app/controllers/ConvertFreeHEP.java)

**Comment by amkhlv** [comment]
I also tried JFreeSVG , with some very strange result. I now have a [table of results here](http://andreimikhailov.com/jlatexmath/)

**Comment by murkle** [comment]
Problem occurs with 
> TeXFormula.SERIF

and
> TeXFormula.SERIF | TeXFormula.BOLD

eg https://www.geogebra.org/m/adJRPZ78

so maybe try with
> TeXFormula.SANSSERIF

or
> TeXFormula.SERIF | TeXFormula.ITALIC

**Comment by calixteman** [comment]
I had a look on this bug and it seems that the italic correction is not taking into account to compute the width of the glyph.

**Comment by calixteman** [comment]
It should be ok with this patch: https://github.com/opencollab/jlatexmath/commit/f6215810cbdde2dba8b85ff2bbe509b420c6a8a2

Thx a lot

**Comment by amkhlv** [comment]
Thank you! This [solved my problem](http://andreimikhailov.com/jlatexmath/)

**Comment by murkle** [comment]
Before patch: https://www.geogebra.org/m/adJRPZ78?cb=jenkins10739
After: https://www.geogebra.org/m/adJRPZ78?cb=jenkins10740

**Comment by amkhlv** [comment]
I want to ask something. Those constants, `TeXFormula.SERIF | TeXFormula.ITALIC`  --- where should I put them? They are parameters to what function? I want to get slanted letters with `JFreeSVG`, how?

**Comment by murkle** [comment]
The spacing for lower-case looks a bit odd now, compare
https://www.geogebra.org/m/PoosXZnO?cb=jenkins10739
https://www.geogebra.org/m/PoosXZnO?cb=jenkins10740

**Comment by calixteman** [comment]
murkle: you're right, I must add italic correction only in math mode.

**Comment by calixteman** [comment]
murkle: you're right, I must add italic correction only in math mode.

**Comment by calixteman** [comment]
I hope that this time all is ok: https://github.com/opencollab/jlatexmath/commit/a3c19750faa3b88c7accda2133c15e7fc3f85d35
@murkle and @amkhlv: please check that all is fine on your side.

**Comment by murkle** [comment]
Thanks, looks good now!
https://www.geogebra.org/m/PoosXZnO?cb=jenkins10747
https://www.geogebra.org/m/adJRPZ78?cb=jenkins10747

**Comment by amkhlv** [comment]
Yes, this is OK. Thank you! By, the way, as off-topic, in [README.md](https://github.com/opencollab/jlatexmath/blob/master/README.md) you have a line : Григорий Яковлевич Перельман shew,
is `shew` a mis-conjugated `show` ? I would write "As was shown by Григорий Яковлевич Перельман: ..." (although, I am not a native English speaker!) unless if this is intentional...

**Comment by calixteman** [comment]
@amkhlv I'm not a native english speaker too so I don't now. For me shew is the past form of show (as far as I remember it's an irregular verb).

**Comment by murkle** [comment]
"shew" should be "showed" 😄
