### ISSUE TITLE
create releases on github

### ISSUE THREAD

**Issue by moritzfl** [opencollab/jlatexmath#11]
According to version.xml the current version is 1.0.5 - it would be nice if github releases reflected that and a offered a jar file for direct download.

**Comment by calixteman** [comment]
@davidmoten could you fix this bug ?

**Comment by davidmoten** [comment]
Sure I'll have a look at it. The convention is to have a tag that points to the code at 1.0.5 release and we'll talk about releasing shortly.

**Comment by moritzfl** [comment]
yes - thats exactly what I meant... I wasn't aware about the progress of the 1.0.5 release and just saw that the tags indicate that the last release was in 2013 with 1.0.3 which I thought was unlikely given the progress made since then in the project.

**Comment by davidmoten** [comment]
I notice 1.0.4 is on Maven Central, deployed 14 Dec 2016. It appears to be the state of the codebase at commit 27ffa7082efa75e6f86e8788f5cbe2156aa15f5c on Oct 24 2016. If that's right then we should create a tag 1.0.4 for that commit. Does this sound right @calixteman?

**Comment by davidmoten** [comment]
If the Maven rework #13 looks ok then we can release 1.0.5 or whatever soon.

@calixteman would you like me to do the first release (once PR is merged)?  For me to have release privileges you'll need to add an issue to the [Sonatype JIRA](https://issues.sonatype.org/secure/Dashboard.jspa) with title "add user for groupId org.scilab.forge" and mention my username davidmoten. It usually happens pretty quickly. The version might be 1.0.5-RC1 if you want to treat it as a release candidate, or we put it out at 1.0.5 and any fixes go in 1.0.6, etc.

**Comment by davidmoten** [comment]
@moritzfl jlatexmath 1.0.5 now on Maven Central. Please give it a try.

**Comment by davidmoten** [comment]
I've also set the tag 1.0.4 on commit 27ffa7082efa75e6f86e8788f5cbe2156aa15f5c.

**Comment by moritzfl** [comment]
1.0.5 seems to work perfectly - no issues so far. Thanks a lot for your work - jlatexmath continues to be very useful for me in multiple projects ;)
