### ISSUE TITLE
add \brack \brace \bangle

### ISSUE THREAD

**Issue by murkle** [opencollab/jlatexmath#19]
Should be easy to backport from our fork, simple adaption of code for choose_macro() for {a \choose b}
http://dev.geogebra.org/trac/changeset/53154

eg
 "{a \brace b}" 
 "{a \bangle b}" 
 "{a \brack b}" 

There's a problem with the first bracket missing from both these which I didn't manage to solve though:
 "{a \bangle b}" 
 "a \atopwithdelims \langle \rangle b" 

I guess it's a font/glyph problem as it's OK in bold (but not italic)

![banglebug](https://cloud.githubusercontent.com/assets/814957/26144155/a93597fe-3adf-11e7-8f96-cca0bb6ef7e4.PNG)

**Comment by calixteman** [comment]
@murkle I'm not able to reproduce your issue with the missing \langle. Could you provide a code ?

**Comment by calixteman** [comment]
@murkle thanks for these macros, I added them: https://github.com/opencollab/jlatexmath/commit/030ef1f5eb49d1a502aca6e578980e2147df51ae.
FYI, you made an error in your code for \brack: the bracket names are lsqbrack and rsqbrack.

**Comment by murkle** [comment]
Oops, thanks!
https://dev.geogebra.org/trac/changeset/54162

**Comment by murkle** [comment]
Please close this ticket (bug went when we consolidated the font info - so it was just something wrong in an XML file in renderer-desktop in our fork)

**Comment by sylvestre** [comment]
ok, thanks
