### ISSUE TITLE
add \longdiv

### ISSUE THREAD

**Issue by murkle** [opencollab/jlatexmath#20]
Easy change if it's wanted 😄 
http://dev.geogebra.org/trac/changeset/51465

eg
123 \longdiv{456}

**Comment by sylvestre** [comment]
Maybe a stupid question but why geogebra is not directly contributing to jlatexmath ?
this would make everyone life easier..

**Comment by calixteman** [comment]
@murkle I implemented the macro \longdiv in this commit: https://github.com/opencollab/jlatexmath/commit/ec84c92f536c3e84e2a9e6c501d01afe38d7d1c2
I fully implemented it to have the same output as in a normal latex distro.
As an example of output:
https://github.com/opencollab/jlatexmath/blob/ec84c92f536c3e84e2a9e6c501d01afe38d7d1c2/jlatexmath/src/test/resources/expected/Example8.png

**Comment by murkle** [comment]
@calixteman very cool, thanks!
