### ISSUE TITLE
\qquad duplicates what follows

### ISSUE THREAD

**Issue by murkle** [opencollab/jlatexmath#21]
From: https://forge.scilab.org/index.php/p/jlatexmath/issues/1571/

Not sure what causes the bug exactly, but changing \qquad to a proper command fixes it, eg
http://dev.geogebra.org/trac/changeset/49606

**Comment by calixteman** [comment]
@murkle what you proposed was just a workaround for a real issue, so I fixed it: https://github.com/opencollab/jlatexmath/commit/9de14def95f0d1082c5abe8902cb001b226ca9f0
By the way, I can add \qquad as a java command (faster)

**Comment by calixteman** [comment]
@murkle I changed \qquad to become a Java command.
