### ISSUE TITLE
Rewrite the parser

### ISSUE THREAD

**Issue by calixteman** [opencollab/jlatexmath#27]
Right now, the parser is slow, bad-designed. So the goal is to have something very fast but it requires to rewrite parser itself and rewrite almost all the macros which take some strings as arguments rather than atom.

**Comment by davidmoten** [comment]
Sounds good. If you like I can contribute jmh benchmarks so you can measure the performance now before changes. I use them in other projects by calling `mvn clean install -P benchmarks`. I would add a sample benchmark that measures the perf of parsing and then rendering to a BufferedImage and you would be able to add whatever additional benchmarks you felt like.

Just before you start doing significant work across the code base I thought to sneak in a PR with a bit of cleanup like removing unused imports, unused constants, add generic types where missing. Just addressing the warnings that an IDE like Eclipse tells you about.  Should I wait till later or is now an ok time?

**Comment by calixteman** [comment]
Go ahead :)
Please make your PR asap.

**Comment by davidmoten** [comment]
@calixteman @sylvestre there are a few changes committed that haven't been released. Shall we release 1.0.6 now?

**Comment by calixteman** [comment]
Yes please

**Comment by calixteman** [comment]
Oh my bad, I closed a non-fixed bug...

**Comment by davidmoten** [comment]
1.0.6 is up on Maven Central. Will be dowloadable in ~10min and indexed by search engines in ~2 hours. I've updated the [Releases](https://github.com/opencollab/jlatexmath/releases) page too.

**Comment by murkle** [comment]
done here:
https://github.com/opencollab/jlatexmath/tree/experimental
