### ISSUE TITLE
Spacing computed from the length of a superscript not subscript even if subscript is longer (in Freeplane)

### ISSUE THREAD

**Issue by vavanade** [opencollab/jlatexmath#3]
Latex code 

`\[||f||_{L^\infty(\mathbb{R}^N)}^{1-\alpha}  ||f||^{\alpha}_{L_1(\mathbb{R}^N)}\]`

 in Freeplane will generate output as in the picture. 

If there is only a subscript, the length is computed from the subscript correctly. Same with supersript.

But if both are used the spacing is NOT computed from the longer one but only from the length of the superscript resulting in a mess as seen in the picture.

This may be an issue of Freeplane (in which case I'm sorry) but I don't have the time to pinpoint it and to me it seems most likely that the issue is caused by this package.

EDIT: In GeoGebra it works just fine so the issue is probably on the side of Freeplane. I am sorry to bother. 
PLEASE CLOSE THIS ISSUE

![jlatexmathissue](https://cloud.githubusercontent.com/assets/24233171/20683637/081fb398-b5ad-11e6-93e7-136ec940cea2.png)

**Comment by murkle** [comment]
Seems OK in GeoGebra (which uses JLaTeXMath), is this the expected output?
https://www.geogebra.org/m/AwZaBry5

**Comment by vavanade** [comment]
murkle: No, the whole L^\infty(\mathbb{R}^N) is supposed to be in the subscript. I have edited the original post because it didn't show the whole equation code ("_" were missing).

**Comment by murkle** [comment]
I get the same problem in GeoGebra 4.2 (October 2013) but not in GeoGebra 4.4 (September 2014) so I guess you just need to use a later version of JLaTeXMath :)

**Comment by calixteman** [comment]
@vavanade is it ok for you with the last version ?

**Comment by vavanade** [comment]
Yes. The've fixed it in the last version of Freeplane. Thanks!
