### ISSUE TITLE
°C doesn't work

### ISSUE THREAD

**Issue by murkle** [opencollab/jlatexmath#36]
`°C`
gets changed to
`\\circC`

Suggested fix:
`parseString.replace(pos, pos + 1, "^\\circ");`
needs to be changed to this in TexParser.java
`parseString.replace(pos, pos + 1, "^{\\circ}");`

Test-case:
` "\rotatebox{90.0}{ \text{ Temperature [°C] }  }" `

**Comment by calixteman** [comment]
Fix in commit: https://github.com/opencollab/jlatexmath/commit/745ff2e225a5bdc4151b93e49fb1ba85562c7038
