### ISSUE TITLE
mhchem Support

### ISSUE THREAD

**Issue by ETHwsch** [opencollab/jlatexmath#40]
We use the mhchem (http://docs.mathjax.org/en/latest/tex.html#mhchem ) package for chemistry when using Latex/MathJax. It lets us easily format chemical formulas and reactions without typing too much.
There really is only one command you need to know here: \ce{...}. \ce{...} takes its parameters and automatically formats it. For example,

$\ce{HCl}$ dissociates in water as follows:
$$\ce{H2O + HCl <=> H3O+ + Cl-}$$

Would it be possible to add mchem to JLatexMath and would it be a big effort to add it to JLatexMath?

Thanks for an answer.

**Comment by murkle** [comment]
Here are some examples:
https://mhchem.github.io/MathJax-mhchem/

From a quick look here, it seems to parse the Chemistry separately (using a lot of Regex) and then convert into LaTeX:
https://github.com/mhchem/MathJax-mhchem/blob/master/unpacked/mhchem.js

To test if that approach would work in JLaTeXMath you could try making a new command `\ce` so that `\ce{anything}`
would always translate to eg
`{\mathrm{CO}{\vphantom{X}}_{\smash[t]{2}} {}+{} \mathrm{C} {}\mathrel{\longrightarrow}{} 2\,\mathrm{CO}}`

**Comment by ETHwsch** [comment]
We are a technical university and we would like to have mhchem support in jlatexmath. Is anybody here who is interested to do this implementation? A offer can sent to me: Werner.schnedl@id.ethz.ch

**Comment by calixteman** [comment]
@ETHwsch, it could be very interesting to work on that.

**Comment by murkle** [comment]
Also some LaTeX commands that mhchem needs will need implementing:

```
\mskip
\mathchoice
\longleftrightarrows
\longrightleftharpoons
\longRightleftharpoons
\longLeftrightharpoons
\tripledash
\lower
\raise
\mkern
```

Quick mockup:
https://www.geogebra.org/m/f9RfmNa7

**Comment by murkle** [comment]
@calixteman can the parser cope with \lower \raise \mkern \mskip with the units mu / pt / em? eg
```
{\mathrm{A}{\rlap{\lower.2em{-}}\rlap{\raise.2em{\tripledash}}-}\mathrm{B}{\rlap{\lower.2em{-}}\rlap{\raise.2em{\tripledash}}-}\mathrm{C}{\rlap{\lower.2em{-}}\rlap{\raise.2em{-}}\tripledash}\mathrm{D}}
{\mathrm{C}{\vphantom{X}}_{\smash[t]{p }}[\mathrm{H}{\vphantom{X}}_{\smash[t]{2}}\mathrm{O}\mskip2mu (\mathrm{l})] {}={} \pu{75.3 J // mol K}}
```


https://www.tutorialspoint.com/tex_commands/mskip.htm
https://www.tutorialspoint.com/tex_commands/lower.htm
https://www.tutorialspoint.com/tex_commands/raise.htm
https://www.tutorialspoint.com/tex_commands/mkern.htm

**Comment by murkle** [comment]
Here's a free-standing version of mhchem (MathJax interface removed), hopefully useful:
http://test.geogebra.org/~mike/mhchem.html
(open the browser's console (F12) to see the output)

If you use Google's RegExp then you can use the JavaScript regexes unaltered (easier for maintenance etc)
https://github.com/gwtproject/gwt/blob/master/user/src/com/google/gwt/regexp/shared/RegExp.java

**Comment by murkle** [comment]
\ce \mathchoice, \mskip, \lower, \raise, \mkern
added here:
https://github.com/opencollab/jlatexmath/tree/experimental
