### ISSUE TITLE
TeXSymbolParser typeMappings init error?

### ISSUE THREAD

**Issue by gameboy120** [opencollab/jlatexmath#43]
env: jvm 1.8.0_45 jlatexmath 1.0.6
input formula string :a/leq b   output image sometimes like this
![test](https://user-images.githubusercontent.com/2542572/38715227-7bc623ec-3f0c-11e8-8aed-2c6dde5b0e9a.jpg)  
or like this 
![test3](https://user-images.githubusercontent.com/2542572/38715252-99e59164-3f0c-11e8-94e4-f947f3ace73b.jpg).

after debug, i find the different, "leq" mapping to a symbol instance ,it's type sometimes 0 and sometimes 3.
![jietu20180413-112639](https://user-images.githubusercontent.com/2542572/38715431-9c86b352-3f0d-11e8-8d36-fe7123207313.jpg)

in fact , "leq" symbol instance's type value should be 3, may be there is something wrong when init?

**Comment by calixteman** [comment]
Strange... 
The only place the type is changed is https://github.com/opencollab/jlatexmath/blob/master/jlatexmath/src/main/java/org/scilab/forge/jlatexmath/TeXParser.java#L717
(by the way, this code is stupid...) 
I managed to have a test case:
a\leq b =>
![image](https://user-images.githubusercontent.com/5641725/38724102-77bd8a32-3f03-11e8-88b0-9d2b6e1b009d.png)

a\leq b {\leq} =>
![image](https://user-images.githubusercontent.com/5641725/38724139-90c83fea-3f03-11e8-944e-77d1eda2013b.png)

The patch should very easy, I'll push it in the next days.

@gameboy120 thx

**Comment by gameboy120** [comment]
👍，waiting for your patch, thank you very much

**Comment by murkle** [comment]
fixed here:
https://github.com/opencollab/jlatexmath/tree/experimental
