### ISSUE TITLE
Does jlatexmath's license permit its distribution with EPL licensed plantuml eclipse plugin?

### ISSUE THREAD

**Issue by jobasto** [opencollab/jlatexmath#49]
Does jlatexmath's license permit its distribution with EPL licensed plantuml eclipse plugin? Please 
see https://github.com/hallvard/plantuml/issues/72#issuecomment-429009840

**Comment by sylvestre** [comment]
From what I could quickly gather, EPL isn't compatible with the GPL2, so, not sure that you can.
(but I am not a lawyer)

**Comment by jobasto** [comment]
I'm wondering about the exception that was added to the jlatexmath's license some time ago:

> As a special exception, the copyright holders of this library give you 
permission to link this library with independent modules to produce 
an executable, regardless of the license terms of these independent 
modules, and to copy and distribute the resulting executable under terms 
of your choice, provided that you also meet, for each linked independent 
module, the terms and conditions of the license of that module. 
An independent module is a module which is not derived from or based 
on this library. If you modify this library, you may extend this exception 
to your version of the library, but you are not obliged to do so. 
If you do not wish to do so, delete this exception statement from your 
version.

**Comment by sylvestre** [comment]
yeah, if you use it this way, this might be good.
Talking for myself (and probably @calixteman ), if your software is FLOSS, I don't care that much :)

**Comment by turesheim** [comment]
Actually, the jlatexmath license clearly states that you cannot use it unless the entire software is GPL. 

> Linking this library statically or dynamically with other modules 
is making a combined work based on this library. Thus, the terms 
and conditions of the GNU General Public License cover the whole 
combination.

Without a classpath exception this makes it very hard to use jlatexmath at all. Maybe you should consider changing the license to something more useful.

**Comment by jobasto** [comment]
@turesheim I understood that the part you cited together with the part I cited both together are the class path exception. Compare http://openjdk.java.net/legal/gplv2+ce.html and https://en.wikipedia.org/wiki/GPL_linking_exception.
I thought that an non-gpl application may link to a library with this class path exception as long as it just "uses" the exported methods, classes, etc. But I might be wrong.
Do you have a definition what "derived from" and "based on" mean in the context of

> An independent module is a module which is not derived from or based
on this library.

?

**Comment by turesheim** [comment]
> @turesheim I understood that the part you cited together with the part I cited both together are the class path exception. Compare http://openjdk.java.net/legal/gplv2+ce.html and https://en.wikipedia.org/wiki/GPL_linking_exception.

My bad. I re-read that part and I think you're correct.

> I thought that an non-gpl application may link to a library with this class path exception as long as it just "uses" the exported methods, classes, etc. But I might be wrong.
> Do you have a definition what "derived from" and "based on" mean in the context of
> 
> > An independent module is a module which is not derived from or based
> > on this library.

I believe by "derived from" and "based on" one means a new library that is either a fork or an extension of jlatexmath.
