### ISSUE TITLE
\neq incorrect After running for a while

### ISSUE THREAD

**Issue by Sean2358** [opencollab/jlatexmath#51]
I have a strange problem. 
The command `\neq` work fine at the beginning，looks like this:
![image](https://user-images.githubusercontent.com/7484066/50676788-3d560400-1031-11e9-91b9-12ea4f40e448.png)

But after running for a while, i don't know when and how,  it is changed: 
![image](https://user-images.githubusercontent.com/7484066/50676721-d3d5f580-1030-11e9-99d6-68680aa6d7bc.png)

Is it because of some other command that changed the environment?

**Comment by Sean2358** [comment]
Lib version is 1.0.7, and the code i use
```
private BufferedImage latex2Img(String latex, float size) {
        TeXFormula formula = new TeXFormula(latex);
        TeXIcon icon = formula.createTeXIcon(TeXConstants.STYLE_DISPLAY, size);
        BufferedImage image = new BufferedImage(icon.getIconWidth(),
                icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = image.createGraphics();
        g2.setStroke(new BasicStroke(1));
        g2.setColor(Color.BLACK);
        JLabel jl = new JLabel();
        jl.setForeground(new Color(0, 0, 0));
        synchronized (this) {
            icon.paintIcon(jl, g2, 0, 0);
        }
        return image;
    }
...
```

**Comment by murkle** [comment]
Is it better with the experimental branch?
https://github.com/opencollab/jlatexmath/tree/experimental

**Comment by Sean2358** [comment]
> Is it better with the experimental branch?
> https://github.com/opencollab/jlatexmath/tree/experimental
Thanks for suggestions! I will try it.
But i don't know the trigger condition for this situation, so it's hard for me to judge whether it is better。
