### ISSUE TITLE
How to use system fonts for letters and numbers？

### ISSUE THREAD

**Issue by ljyao** [opencollab/jlatexmath#53]

**Comment by sylvestre** [comment]
please don't use issue for support requests

**Comment by ClementGre** [comment]
Hi @sylvestre,
I have some issues with loading fonts/cyrillic "artefact".

I searched a lot on the web, but there is no documentation about JLatexMath.
You said "don't use issue for support requests", but yo do not told us any way to find documentation about the library. The Javadoc is incomplete, and I can't find how to load the cyrillic "artefact".

I would be grateful if you would be able to give me a real documentation about how to load this kind of font.
All the best, Clément Grennerat

**Comment by sylvestre** [comment]
we don't have documentation. you should have a look to how Scilab or Geogebra do it.
