### ISSUE TITLE
\hfil,\hfilll support

### ISSUE THREAD

**Issue by ljyao** [opencollab/jlatexmath#61]
\hfil,\hfilll is not supported, how to replace it？

**Comment by murkle** [comment]
What do you want to do exactly? Can you post a PNG showing what you want?

**Comment by ljyao** [comment]
> What do you want to do exactly? Can you post a PNG showing what you want?

\{\begin{array}{l}x+y=100\hfill \\ 3x+y=100\hfill \end{array}
![image](https://user-images.githubusercontent.com/13914318/70507855-33ede980-1b68-11ea-9be7-ce2634e92fca.png)

**Comment by ljyao** [comment]
> What do you want to do exactly? Can you post a PNG showing what you want?
\matrix{
11111&22222&33333\\
a&b&\hfill c
}
![image](https://user-images.githubusercontent.com/13914318/70514046-c8a71600-1b6d-11ea-9df9-88889e1f0b45.png)
c is aligned with 33333

**Comment by murkle** [comment]
Try this

` {\begin{array}{ccr}11111&22222&33333 \\ a&b&c \\ \end{array}}`
