### ISSUE TITLE
Retain the variable names of formula in the svg image?

### ISSUE THREAD

**Issue by balajivignesh258** [opencollab/jlatexmath#67]
Very nice work! I am using this to print formulas and it works very well.

I need some help. I'm in need of retaining the variable names in the exported svg image.

When using the constructor of SVGGraphics2D there is an option to use font instead of shapes in the resulting svg image. But using font instead of shapes, does not paint the mathematical formula nicely.

```javascript
SVGGraphics2D g2 = new SVGGraphics2D(ctx, fontAsShapes);
```

I require the variables names for post processing the svg image to embed hyperlinks. Thanks!

This is the result I get passing fontAsShape as false
![font](https://user-images.githubusercontent.com/17313801/91851945-a7e39b00-ec7d-11ea-85fb-99a30ea1aa61.png)
This is the result I get passing fontAsShape as true
![1598963872683_shape](https://user-images.githubusercontent.com/17313801/91852179-16c0f400-ec7e-11ea-8d33-b4eeb92a07c6.png)

So in the above formula is it possible to group the entire variable End_fD in a single svg text group?

**Comment by murkle** [comment]
Maybe you can use SVG groups and add the variable name in a comment. See here for how to do that:

https://github.com/geogebra/geogebra/blob/master/desktop/src/main/java/org/geogebra/desktop/export/SVGExtensions.java

**Comment by balajivignesh258** [comment]
Thank you for the quick reply. I have updated the question with some example for reference. Like in the example, is it possible to group the entire variable name as selectable text?

**Comment by murkle** [comment]
Only if you split the formula into 2 I think
