### ISSUE TITLE
Separate LaTeX, TeX, TeX Math, and ConTeXt

### ISSUE THREAD

**Issue by ghost** [opencollab/jlatexmath#68]
What are your thoughts on having separate modules (or packages) that allow developers to easily pick and choose what TeX flavours they'd like to bundle with their applications? 

It would require changes to the project's organizational structure. See my fork of [JMathTex](https://github.com/DaveJarvis/JMathTeX) for details, most relevant would be the [resource readers](https://github.com/DaveJarvis/JMathTeX/tree/master/src/main/java/be/ugent/caagt/jmathtex/resources) and [resource hierarchy](https://github.com/DaveJarvis/JMathTeX/tree/master/src/main/resources). Broadly, consider:

# Java
Under `src/main/java/`:

* org/scilab/forge/jlatexmath/tex
* org/scilab/forge/jlatexmath/latex
* org/scilab/forge/jlatexmath/context
* org/scilab/forge/jlatexmath/mathtex

# Resources
Under `src/main/resources/`:

* config/tex/*.xml
* config/latex/*.xml
* config/mathtex/*.xml
* config/context/*.xml

# Fonts
Under `src/main/resources/fonts/`:

* cm/*.ttf

**Comment by murkle** [comment]
There are some major changes in JLaTeXMath 2 over what's currently in master. You can see that here https://github.com/opencollab/jlatexmath/tree/experimental

In particular there are no longer any XML files, not sure how that affects your idea

**Comment by ghost** [comment]
> In particular there are no longer any XML files, not sure how that affects your idea

It's not so much about the XML files as it is about making the build process quick and easy to identify and remove (or include) portions of the library that are specific to LaTeX, TeX, ConTeXt, etc.

To be a bit more concrete, consider:

    gradle clean build --compatability latex
    gradle clean build --compatability context
    gradle clean build --compatability tex
    gradle clean build --compatability katex
    gradle clean build --compatability etex
    gradle clean build --compatability bibtex
    gradle clean build --compatability mathtex

In the first case, `jt-latex.jar` is produced that can render LaTeX. In the second case, `jt-context.jar` is produced that can render ConTeXt. In the third case, `jt-tex.jar` is produced that has only bare-bones TeX support. In the last case, `jt-mathtex.jar` is produced that has support for TeX and most Math macros that are common across all other *TeX flavours.

This leads naturally to extensions such as:

    gradle clean build --compatability tex --exports pdf,svg,png,swing
    gradle clean build --compatability latex --exports javafx --uberjar

The second example would create an uber jar that contains all necessary dependencies to integrate LaTeX into a JavaFX application (so no code that exports to Swing is included).

**Comment by murkle** [comment]
Speaking personally there doesn't seem to be too much of interest in http://www.berenddeboer.net/tex/LaTeX2ConTeXt.pdf

I think most (all?) users of JLaTeXMath just want to render things like \sqrt{\frac{...

**Comment by murkle** [comment]
Not sure about JavaFX, if the "desktop" version here doesn't work then I think it wouldn't be too much work to make a "javafx" one
https://github.com/opencollab/jlatexmath/tree/experimental/jlatexmath/src/main/java/org/scilab/forge/jlatexmath

desktop+shared == Java
web+shared = HTML5

**Comment by ghost** [comment]
> Speaking personally there doesn't seem to be too much of interest

Isn't that [argumentum ad populum](https://philosophy.lander.edu/logic/popular.html)? It seems the [mailing list](https://mailman.ntg.nl/pipermail/ntg-context/2020/thread.html), [SE network](https://tex.stackexchange.com/questions/tagged/context?tab=Newest), and [Pandoc](https://www.google.com/search?q="ConTeXT"+site%3Agithub.com+inurl%3Ajgm%2Fpandoc+2019|2020) show an active interest in ConTeXt; [Aditya](https://adityam.github.io/context-blog/) could probably chime in with more details about its status.

> I think most (all?) users of JLaTeXMath just want to render things like \sqrt{\frac{...

Agreed 100%, most users want simple equations. Hence suggesting "mathtex" as one of the possible exports, which would cover the basics, allowing developers to leave out the complexity of other *TeX flavours (such as supporting macros from common LaTeX packages).

**Comment by calixteman** [comment]
I implemented some stuff to have some packages usable with `\usepackage` command and which could help with what you want, but it seems that it has been removed (the only reference to JLMPackage class is in the test FooPackage.java).
@murkle maybe you could re-add them, as far as I remember there is not so much code for that and I think it's useful. Wdyt ?

**Comment by murkle** [comment]
IIRC that got removed as it was the only place where clone() was needed and used (not supported in GWT).

Originally duplicate() method was introduced as a workaround which was pretty horrible https://github.com/opencollab/jlatexmath/commit/a0bf906d9150716a659c107edd7fe6fd1710127b

@calixteman do you think it's possible to add it back in a neater way?

@DaveJarvis JLaTeXMath is a library so it's only interesting (for me) what the users of the library need (not "the internet")

**Comment by calixteman** [comment]
@murkle Could you give me the commit where it has been removed ?

**Comment by murkle** [comment]
https://github.com/opencollab/jlatexmath/commit/27a5a5e1da577640d34fd210e4142fe9ae192d4f

**Comment by calixteman** [comment]
An idea could to add back the duplicate method but only `PackagedCommand` which could return `this` when it's a "one way" command or a kind of "clone" when it isn't.
And add in the javadoc of this method that in order to be used in GWT context, this method mustn't use `clone` but use a copy constructor.
As far as I remember, depending of the context, a previous `RowAtom` can be modified so if the command doesn't return a "clone" then any modification in this `RowAtom` will imply that all the next uses of the command will give a corrupted `RowAtom` (it's a bug we've in master).
@DaveJarvis, maybe you could have a look on that stuff and if it's fine for your needs, you can probably make a PR.

**Comment by ghost** [comment]
My [text editor](https://github.com/DaveJarvis/scrivenvar/) ([video](https://www.youtube.com/watch?v=u_dFd6UhdV8)) supports Markdown, R Markdown, and more. The editor lacks a TeX engine; an [issue](https://github.com/DaveJarvis/scrivenvar/issues/69) describes possible integration approaches. [εχTeX](https://github.com/DaveJarvis/extex), while expansive, needs _a lot_ more work and lacks [JMathTex](http://jmathtex.sourceforge.net/)'s simplicity. JMathTeX is super-easy to integrate, but lacks critical functionality, and is a bit buggy (such as `\vec{u}` being misaligned, typographically).

JLaTeXMath has the critical functionality, but comes with a lot of LaTeX code that's tightly coupled. In my Typesetting Markdown series, the [math section](https://dave.autonoma.ca/blog/2019/08/06/typesetting-markdown-part-7/#math) of part 7 shows the output from running ConTeXt on a Markdown document that has embedded TeX code. I'd like to give the editor the ability to include math-related TeX commands---those simple equations we wrote about---that are rendered in real-time as SVG documents, without bundling in LaTeX code.

I don't know (and couldn't find) an exhaustive list of all TeX commands and all LaTeX commands, so I'm not in a position to know what's essential for TeX vs. LaTeX. For example, `\usepackage` is a LaTeX command that doesn't compile in ConTeXt, but `\big` (or similar) isn't a plain TeX macro although it compiles in both ConTeXt and LaTeX---so I'd consider it as part of "math TeX". For the editor, `\big` would probably be included while `\usepackage` would not. (If this example is wrong, my apologies, but hopefully you get the idea.)

>  maybe you could have a look on that stuff and if it's fine for your needs, you can probably make a PR.

More specific, please---what stuff? (Please link to the commits / source code and provide further details about what would have to change, if possible.)

**Comment by murkle** [comment]
@DaveJarvis OK, so the first step is for you to make a PR to add a javafx package here (hopefully quite easy to adapt desktop)
https://github.com/opencollab/jlatexmath/tree/experimental/jlatexmath/src/main/java/org/scilab/forge/jlatexmath

2nd step: adapt your editor to use (javafx + share) to allow just LaTeX input

3rd step: we can think about the abstractions you've suggested and make a plan

**Comment by ghost** [comment]
> 2nd step: adapt your editor to use (javafx + share) to allow just LaTeX input

My plan is to use JMathTeX, borrowing fixes from JLaTeXMath, until plain math TeX is available. I'm not sure if I sufficiently emphasized that I do not want to publish a version of my editor with LaTeX support. (If people start using LaTeX, then I can't remove the functionality without breaking their documents.)

The JavaFX isn't as important to me as the separation of *TeX flavours: it was an example of feature separation that's not currently present the code base. By which I mean that it is not currently possible to generate a JAR file without Swing-specific code. The editor will export SVG, so whether Swing or JavaFX is used is inconsequential. (ProGuard can safely eliminate all unused classes from JAR files, provided no reflection is being used. If reflection is used, then the project would have to communicate where reflection happens so that the analysis can produce the minimal set of required classes.)
