### ISSUE TITLE
[Question] How to produce XML files from TTF?

### ISSUE THREAD

**Issue by ForNeVeR** [opencollab/jlatexmath#7]
Hello! I am maintaining another JMathTeX satellite project, [WPF-Math](https://github.com/ForNeVeR/wpf-math), and I want to ask you a question about the legacy XML font description JMathTeX is using.

I can see that you're using and successfully modifying the same [XML font format](https://github.com/opencollab/jlatexmath/blob/7b99ab584bd8598194d35f60965bda9eac92d641/src/org/scilab/forge/jlatexmath/fonts/base/jlm_cmex10.xml), and these XML files are obviously linked to the corresponding TTF files.

I'm curious: how are you extracting these XML files from the newly added fonts? How are you modifying these files? Are there any tools or scripts for that?

I've tried to ask JMathTeX author, Kris Coolsaet, but unfortunately it was so long ago that he didn't remember how these XML files were managed back then.

**Comment by calixteman** [comment]
As far as I remember, I used ttf2tfm to generate the a VPL file and I wrote a lisp script to generate the XML from it. I don't have this script anymore but it's very easy to write a converter.

**Comment by ForNeVeR** [comment]
@calixteman thanks a lot! I have no problems writing such a script myself after I'll get all the inputs. Could you please elaborate a little more?

For example, after I execute `ttf2tfm jlm_cmex10.ttf -v jlm_cmex10.vpl`, I have the following output:

```
(CHARACTER O 173 (comment braceleft)
   (CHARWD R 450)
   (CHARHT R 120)
   (CHARDP R 213)
   (CHARIC R 24)
   (MAP
      (SETCHAR O 133)
      )
   )
```

While in the corresponding [`jlm_cmex10`](https://github.com/opencollab/jlatexmath/blob/7b99ab584bd8598194d35f60965bda9eac92d641/src/org/scilab/forge/jlatexmath/fonts/base/jlm_cmex10.xml) there're numbers such as 
```xml
<Char code="161" width="0.458336" height="0.039999" depth="1.160013" >
```

How do I convert numbers from VPL to the corresponding XML? Here's the full VPL file in case it'll be easier for you to answer if you can look at it: https://gist.github.com/ForNeVeR/e3f34a2d9138dc77574a24b073e11c66

**Comment by calixteman** [comment]
ttf2tfm is used to generate metrics (tfm) from the glyphes themselves, but as you know the real used metrics may differ from the glyphes' ones. So with cmex10.ttf you've the file cmex10.tfm and in using tftopl you should be able to get metrics used to layout the glyphes in human readable format.

**Comment by ForNeVeR** [comment]
@calixteman aha, got that. Thanks a lot for your explanations!
