### ISSUE TITLE
Performance: replace exceptions used for conditional logic

### ISSUE THREAD

**Issue by ghost** [opencollab/jlatexmath#70]
Guided by [async profiler](https://github.com/jvm-profiling-tools/async-profiler), I've made some improvements to my fork of [JMathTeX](https://github.com/DaveJarvis/JMathTeX) that may be relevant. [JMH](https://openjdk.java.net/projects/code-tools/jmh/) notwithstanding it appears that the time to parse TeX has been halved. The output documents are not _perfectly_ identical, but close enough to show the performance gains---see below for one hot spot.

Once @murkle's changes are on the mainline branch, we'll see how much performance is gained from the updates.

# Test Setup

This section describes the setup for the two code bases.

## Equations

The following expressions were tested:

``` java
  private final static String[] EQUATIONS = {
      "(a+b)^2=a^2 + 2ab + b^2",
      "S_x = sqrt((SS_x)/(N-1))",
      "e^{\\pi i} + 1 = 0",
      "\\sigma=\\sqrt{\\sum_{i=1}^{k} p_i(x_i-\\mu)^2}",
      "\\sqrt[n]{\\pi}",
      "\\sqrt[n]{|z| . e^{i \\theta}} = " +
          "\\sqrt[n]{|z| . e^{i (\\frac{\\theta + 2 k \\pi}{n})}}," +
          " k \\in \\lbrace 0, ..., n-1 \\rbrace, n \\in NN",
      "\\vec{u}^2",
      "\\sum_{i=1}^n i = (\\sum_{i=1}^{n-1} i) + n =\n" +
          "\\frac{(n-1)(n)}{2} + n = \\frac{n(n+1)}{2}",
      "\\int_{a}^{b} x^2 dx",
      "G_{\\mu \\nu} = \\frac{8 \\pi G}{c^4} T_{{\\mu \\nu}}",
      "\\prod_{i=a}^{b} f(i)",
  };
```

## JMathTeX Fork

Two loops, one through the equations and the other to parse 10,000,000 plain TeX strings.

``` java
    final var size = 20f;
    final var texFont = new DefaultTeXFont( size );

    final long startTime = System.currentTimeMillis();

    for( int j = 0; j < EQUATIONS.length; j++ ) {
      // Unused, but doesn't affect the outcome.
      final var filename = "/tmp/eq-" + j + ".svg";

      for( int i = 0; i < 10_000_000 / EQUATIONS.length; i++ ) {
        final var formula = new TeXFormula( EQUATIONS[ j ] );
        final var env = new TeXEnvironment( STYLE_DISPLAY, texFont );
        final var box = formula.createBox( env );
        final var layout = new TeXLayout( box, size );
      }
    }

    System.out.println( System.currentTimeMillis() - startTime );
```

## JLaTeXMath

First, strip down `Convert.toSVG` to its TeX parsing parts:

``` java
    public static void toSVG(String latex, String file, boolean fontAsShapes) throws IOException {
        final TeXFormula formula = new TeXFormula(latex);
        final TeXIcon icon = formula.createTeXIcon(TeXConstants.STYLE_DISPLAY, 20);
        icon.setInsets(new Insets(5, 5, 5, 5));
        final Dimension dim = new Dimension(icon.getIconWidth(), icon.getIconHeight());
    }
```

Then change `Example5` to:

``` java
  public static void main( String[] args ) throws IOException {
    final long startTime = System.currentTimeMillis();

    for( int j = 0; j < EQUATIONS.length; j++ ) {
      for( int i = 0; i < 10_000_000 / EQUATIONS.length; i++ ) {
        Convert.toSVG( EQUATIONS[ j ], "/tmp/example-" + j + ".svg", true );
      }
    }

    System.out.println( System.currentTimeMillis() - startTime );
  }
```

# Benchmarks

Results with 1 run each (no best of times):

* JLaTeXMath ran in 92618 milliseconds (1.54 minutes).
* JMathTeX fork ran in 41019 milliseconds (0.68 minutes).

Three runs of 10,000 iterations after further micro-optimizations to JMathTeX fork:

* JLaTeXMath: 1039 ms, 1027 ms, 1166 ms
* JMathTeX fork: 239 ms, 219 ms, 227 ms

This gets the code within poking distance of real-time rendering for documents of significant size.

# Gains

One of the larger performance gains was to eliminate using exceptions for conditional logic in `TeXParser`'s `processEscape()` method. The following code is slow because Java will fill out an entire stack trace when a formula or a symbol cannot be found:

``` java
        try {
            return TeXFormula.get(command).root;
        } catch (FormulaNotFoundException e) {
            try {
                return SymbolAtom.get(command);
            } catch (SymbolNotFoundException e1) { }
        }
```

Instead, consider using `Optional` or return `null` instead. The `processEscape()` method is in a critical part of the code.

**Comment by calixteman** [comment]
@DaveJarvis could you test with experimental branch ? it should be a way faster.

**Comment by ghost** [comment]
1. git clone https://github.com/opencollab/jlatexmath.git
1. cd jlatexmath
1. git checkout 27a5a5e
1. mvn package

The branch doesn't compile. Please specify the exact branch name to check out and I'll try again.

**Comment by ghost** [comment]
Closing as this doesn't appear relevant to the experimental branch's `TeXParser` class.
