### ISSUE TITLE
\cancel isn't supported?

### ISSUE THREAD

**Issue by abdelfattahradwan** [opencollab/jlatexmath#73]
Hello,

I have recently started using jlatexmath in one of my projects and found out that \cancel isn't supported.

When I try to render a formula with \cancel it results in the following error:

![2020-11-21_23-51-28](https://user-images.githubusercontent.com/37028872/99888304-7cf15d80-2c54-11eb-97c1-a67cf4c8a46b.png)

I hope someone can help with this.

Thanks.

**Comment by murkle** [comment]
Use the experimental branch, that has loads of improvements

**Comment by abdelfattahradwan** [comment]
> Use the experimental branch, that has loads of improvements

@murkle could you please tell me how (what is the proper artifact ID to use I mean) ? I'm using maven. Also, it it stable enough to be used in production?

**Comment by abdelfattahradwan** [comment]
@murkle when building the experimental version, the build fails with errors relating to something in `Opentype.java` and `com.google.*` packages not existing.

**Comment by murkle** [comment]
Are the compile errors in the tests, or somewhere important?

Stable: yes - very 

Maven: sorry, no

**Comment by abdelfattahradwan** [comment]
> Are the compile errors in the tests, or somewhere important?
> 
> Stable: yes - very
> 
> Maven: sorry, no

The errors are related to the tests yeah.

**Comment by murkle** [comment]
OK, you can either ignore the errors or try to fix them of course :)

**Comment by abdelfattahradwan** [comment]
> OK, you can either ignore the errors or try to fix them of course :)

Well, 99.9% of the errors are related to missing symbols but when I go to the files where it says they're missing, I find everything in place, also ignoring them, when I import the generated jars GraphicsFactory is always null, and TeXFormula is missing all create* methods?!

**Comment by abdelfattahradwan** [comment]
@murkle Also, when I do `mvn clean install -fn` it still doesn't output jars :(

**Comment by abdelfattahradwan** [comment]
I have attached a file containing the resulting logs of running `mvn clean install -fn -X` inside the jlatexmath folder

[build.txt](https://github.com/opencollab/jlatexmath/files/5579972/build.txt)

**Comment by murkle** [comment]
The "web" package is just for use with GWT

**Comment by abdelfattahradwan** [comment]
Okay then, I'm sorry if I'm taking much of your time, but can you please tell me how to properly build this thing?! I swear I have been trying all day with no success!!

**Comment by abdelfattahradwan** [comment]
@murkle any help possible or I will just have to wait until you guys release the new version?

**Comment by murkle** [comment]
It should work if you delete the "web" package and testing bits

**Comment by abdelfattahradwan** [comment]
@murkle 

- Deleted 'web'.
- Deleted 'test'.
- Built using 'mvn clean install'
- Added the library to my project.
- `new TeXFormula("x")` is missing `createPNG`
- `new TeXFormula("x").createBufferedImage(TeXConstants.STYLE_DISPLAY, 36.0d, Colors.WHITE, Colors.BLACK)` fails with:

![2020-11-23_19-08-20](https://user-images.githubusercontent.com/37028872/99992640-41bf6d80-2dbf-11eb-9678-27348a2d7386.png)

- `new TeXFormula("2x + x")` fails with:

![2020-11-23_19-09-09](https://user-images.githubusercontent.com/37028872/99992703-5ef43c00-2dbf-11eb-9618-987b0d49b704.png)

**Comment by murkle** [comment]
Can you run https://github.com/opencollab/jlatexmath/blob/experimental/jlatexmath/src/main/java/org/scilab/forge/jlatexmath/desktop/TestJlmDesktop.java ?

**Comment by abdelfattahradwan** [comment]
> Can you run https://github.com/opencollab/jlatexmath/blob/experimental/jlatexmath/src/main/java/org/scilab/forge/jlatexmath/desktop/TestJlmDesktop.java ?

Excuse my inexperience but how do I run this test alone?

**Comment by murkle** [comment]
It's not a test - it has this. Just run it:
```
public static void main(String[] args) {
		Configuration.getFontMapping();
		TestJlmDesktop s = new TestJlmDesktop();
		s.setVisible(true);
	}
```

**Comment by abdelfattahradwan** [comment]
@murkle 

Result:

TestJlmDesktop.java:9: error: package org.scilab.forge.jlatexmath.desktop.graphics does not exist
import org.scilab.forge.jlatexmath.desktop.graphics.Graphics2DD;
                                                   ^
TestJlmDesktop.java:10: error: package org.scilab.forge.jlatexmath.share does not exist
import org.scilab.forge.jlatexmath.share.Colors;
                                        ^
TestJlmDesktop.java:11: error: package org.scilab.forge.jlatexmath.share does not exist
import org.scilab.forge.jlatexmath.share.Configuration;
                                        ^
TestJlmDesktop.java:12: error: package org.scilab.forge.jlatexmath.share does not exist
import org.scilab.forge.jlatexmath.share.TeXConstants;
                                        ^
TestJlmDesktop.java:13: error: package org.scilab.forge.jlatexmath.share does not exist
import org.scilab.forge.jlatexmath.share.TeXFormula;
                                        ^
TestJlmDesktop.java:14: error: package org.scilab.forge.jlatexmath.share.platform does not exist
import org.scilab.forge.jlatexmath.share.platform.FactoryProvider;
                                                 ^
TestJlmDesktop.java:15: error: package org.scilab.forge.jlatexmath.share.platform.graphics does not exist
import org.scilab.forge.jlatexmath.share.platform.graphics.Image;
                                                          ^
TestJlmDesktop.java:20: error: cannot find symbol
                if (FactoryProvider.getInstance() == null) {
                    ^
  symbol:   variable FactoryProvider
  location: class TestJlmDesktop
TestJlmDesktop.java:21: error: cannot find symbol
                        FactoryProvider.setInstance(new FactoryProviderDesktop());
                                                        ^
  symbol:   class FactoryProviderDesktop
  location: class TestJlmDesktop
TestJlmDesktop.java:21: error: cannot find symbol
                        FactoryProvider.setInstance(new FactoryProviderDesktop());
                        ^
  symbol:   variable FactoryProvider
  location: class TestJlmDesktop
TestJlmDesktop.java:37: error: cannot find symbol
                Graphics2DD g2d = new Graphics2DD(g2);
                ^
  symbol:   class Graphics2DD
  location: class TestJlmDesktop
TestJlmDesktop.java:37: error: cannot find symbol
                Graphics2DD g2d = new Graphics2DD(g2);
                                      ^
  symbol:   class Graphics2DD
  location: class TestJlmDesktop
TestJlmDesktop.java:61: error: cannot find symbol
                        TeXFormula formula = new TeXFormula(text);
                        ^
  symbol:   class TeXFormula
  location: class TestJlmDesktop
TestJlmDesktop.java:61: error: cannot find symbol
                        TeXFormula formula = new TeXFormula(text);
                                                 ^
  symbol:   class TeXFormula
  location: class TestJlmDesktop
TestJlmDesktop.java:62: error: cannot find symbol
                        Image im = formula.createBufferedImage(TeXConstants.STYLE_DISPLAY,
                        ^
  symbol:   class Image
  location: class TestJlmDesktop
TestJlmDesktop.java:62: error: cannot find symbol
                        Image im = formula.createBufferedImage(TeXConstants.STYLE_DISPLAY,
                                                               ^
  symbol:   variable TeXConstants
  location: class TestJlmDesktop
TestJlmDesktop.java:63: error: cannot find symbol
                                        30, Colors.BLACK, Colors.WHITE);
                                            ^
  symbol:   variable Colors
  location: class TestJlmDesktop
TestJlmDesktop.java:63: error: cannot find symbol
                                        30, Colors.BLACK, Colors.WHITE);
                                                          ^
  symbol:   variable Colors
  location: class TestJlmDesktop
TestJlmDesktop.java:70: error: cannot find symbol
                Configuration.getFontMapping();
                ^
  symbol:   variable Configuration
  location: class TestJlmDesktop
19 errors

**Comment by abdelfattahradwan** [comment]
@murkle any idea what's causing the error above?

**Comment by abdelfattahradwan** [comment]
@murkle any update?!

**Comment by sylvestre** [comment]
afaik, it is still happening. Why did you close it @murkle ?

**Comment by murkle** [comment]
See https://github.com/opencollab/jlatexmath/issues/18

**Comment by sylvestre** [comment]
@murkle please add a comment then...
