### ISSUE TITLE
How to generate minimal jar?

### ISSUE THREAD

**Issue by snecklifter** [opencollab/jlatexmath#77]
Since the change to maven, it seems the ability to generate the -minimal JAR is no longer an option however it is used by https://github.com/asciidoctor/asciidoctor-diagram and we have an open issue for this: https://github.com/asciidoctor/asciidoctor-diagram/issues/314

Any ideas if this is still possible?

**Comment by murkle** [comment]
The minimal jar option was made when Java Applets were a thing - so personally speaking I don't see a need for it any more.

The active version (basically jlm v2) is in the experimental branch so I suggest you evaluate using that for asciidoctor instead, OK?
