### ISSUE TITLE
Could anyone help me with the information about any new releases or new versions of JlatexMath after JlatexMath-1.0.7?

### ISSUE THREAD

**Issue by kulkpraful** [opencollab/jlatexmath#83]
I would like to know, is there any new version released for jlatexmath library after 1.0.7?

**Comment by murkle** [comment]
Check the "experimental" branch for the current version

**Comment by davidmoten** [comment]
@murkle we should update that branch for release to Maven Central don't you think? It's much more useful to people as a versioned artifact there.

**Comment by murkle** [comment]
Sounds good to me! I have no knowledge about how to do that though
