### ISSUE TITLE
Why garbled

### ISSUE THREAD

**Issue by tutuerhao** [opencollab/jlatexmath#89]
![image](https://user-images.githubusercontent.com/29938085/139414232-956efbf9-e0a8-4333-a784-e008b3f53e51.png)

formula：\overrightarrow a=(1，2)，\overrightarrow b=(-2，3)，2\underset{}{\overrightarrow a}+3\overrightarrow b=\_。
use springboot 2.2.7.RELEASE and jdk11

**Comment by murkle** [comment]
Try the experimental branch. Does this look like what you expect?

![image](https://user-images.githubusercontent.com/814957/139436929-e0c4dd96-f7f3-45a6-9db1-cf1755ddc729.png)

**Comment by murkle** [comment]
Maybe try using pure LaTeX rather than mixing in Unicode characters

`\\overrightarrow a=(1\uFF0C2)\uFF0C\\overrightarrow b=(-2\uFF0C3)\uFF0C2\\underset{}{\\overrightarrow a}+3\\overrightarrow b=_\u3002`

**Comment by tutuerhao** [comment]
> Unicode 字符

If I want use Unicode characters，what I need to do？

**Comment by tutuerhao** [comment]
Because My mysql stored so much this data，but I can‘t change this

**Comment by tutuerhao** [comment]
I successed when I replace Chinese code to English code，So thank you very much~

**Comment by tutuerhao** [comment]
Hei Mr.murkle ，I see Chinese in my system，e.g:`由\vert x-2\vert<1\mathrm{可知}，-1<x-2<1，\\即1<x<3，\mathrm{故不等式的解集为}\{x\vert1<x<3\}`,What  do I do?

**Comment by tutuerhao** [comment]
Sorry Mr.murkle ，I see Chinese in my system，e.g:`由\vert x-2\vert<1\mathrm{可知}，-1<x-2<1，\\即1<x<3，\mathrm{故不等式的解集为}\{x\vert1<x<3\}`,What  do I do?

**Comment by murkle** [comment]
Have you tried the experimental branch?

![image](https://user-images.githubusercontent.com/814957/139527224-88b9dfb9-4cb9-42fa-a102-18967a48d323.png)

**Comment by tutuerhao** [comment]
experimental branch can not compile

**Comment by tutuerhao** [comment]
Openjdk less Chinese Font， I was successed than I added to Chinese Font，Thank you very much~

**Comment by sylvestre** [comment]
@murkle maybe this branch should be merged into main and we should ship a new release (with a bump of the major version) ?

**Comment by murkle** [comment]
I definitely agree but it's not going to magically happen on its own
