### ISSUE TITLE
SVG groups for each line

### ISSUE THREAD

**Issue by MykolaGolubyev** [opencollab/jlatexmath#9]
Hello,
thanks a lot for this library.

A question here. Is there a way to group equations  into SVG groups? I am trying to render one line at a time and it will be easy to achieve if there are distinct groups.

**Comment by calixteman** [comment]
Hi,
I don't know. My first goal was to be able to draw equations in anything implementing Graphics2D.
AFAIK, this concept of "groups" doesn't have any sense in a Graphics2D.
An idea could be to add a new command (e.g. \jlmSVGGroup{hello}) which will create a box which will "draw" a group when the box is rendering but only when the Graphics2D is a SVGGraphics2D.
By the way, I don't want to add a dependency on batiks or anything else. So a good start point could be to try to write you own package, as an example: https://github.com/opencollab/jlatexmath/blob/master/examples/Macros/FooPackage.java
I don't know if this feature is ok (ie add a package) so you could try and give me some feedback.

**Comment by murkle** [comment]
If it's any help, you can extend FreeHEP's SVGGraphics2D like this, which we use for grouping layers:
https://github.com/geogebra/geogebra/blob/master/desktop/src/main/java/org/geogebra/desktop/export/SVGExtensions.java

Not sure how you'd make sure startGroup() and endGroup() are called at the right time though, maybe Calixte's suggestion can help there!

**Comment by MykolaGolubyev** [comment]
Thank you for the suggestions. Ideally I would like to do it without any custom syntax. And instead understand when a line is ended. Especially for cases when equations are aligned with = sign.

**Comment by calixteman** [comment]
Could you give an example of what you want exactly ?

**Comment by MykolaGolubyev** [comment]
I want each line in multiline assignments (\begin{array}{lcl} z & = & a \\ f(x,y,z) & = & x + y + z \end{array}) to have a group. So I can reveal one group at a time.

**Comment by murkle** [comment]
Does it have to be in one SVG?

Why not make 3 using \phantom{}? eg

` (\begin{array}{lcl} z & = & a \ f(x,y,z) & = & x + y + z \end{array})`

`(\begin{array}{lcl} z & = & a \ f(x,y,z) & = & \phantom{x + y + z} \end{array})`

`(\begin{array}{lcl} z & = & \phantom{a \ f(x,y,z)} & = & \phantom{x + y + z} \end{array})`

**Comment by MykolaGolubyev** [comment]
Yes if possible I would prefer my clients to specify formula deduction steps as one latex expression.
