### ISSUE TITLE
TeXFormula throws ParseException error

### ISSUE THREAD

**Issue by ghost** [opencollab/jlatexmath#94]
I am trying to parse the following LaTex on an Android app:
`\[\begin{align} & \text{Suppose a cube is cut open } \\ & \text{and folded out}\text{. }\!\!~\!\!\text{ Which of } \\ & \text{the following nets will not } \\ & \text{give a cube when folded up?} \\ \end{align}\]`

But when parsing the string using `TeXFormula formula = new TeXFormula(builder);` the following exception is thrown:

org.scilab.forge.jlatexmath.ParseException: Problem with command [ at position 0:236

I think it has to do with the following sequence of symbols: `~\!`.

Could someone please help me?

I have the following line in my TeXFormula.class: `public static final java.lang.String VERSION = "1.0.3";`

**Comment by murkle** [comment]
Seems OK to me - please try in the **experimental** branch

**Comment by ghost** [comment]
Thank you for your response. 

One more question: How do I find the char at position 0:236 given in the error message?
