### ISSUE TITLE
Nested fractions inside parentheses

### ISSUE THREAD

**Issue by pablogzlezmora** [opencollab/jlatexmath#95]
Could this equation be fenced inside parentheses, keeping aligned _P_ variable, equal sign, and main fraction line, without a space over the 3414 main numerator?
```P= \dfrac{3414}{1+\dfrac{\dfrac{1}{6}}{100}}```
![image](https://user-images.githubusercontent.com/38077825/165196516-25664de2-3397-4503-b24b-f3df0b316074.png)
Please, excuse me if this is not the place for this question.

**Comment by murkle** [comment]
Try
`P= \left( \dfrac{3414}{1+\frac{\frac{1}{6}}{100}} \right)`
