### ISSUE TITLE
latex \left\{ \begin{array}[1]\\2x+y=4 \\ x+2y=5 \\\end{array} \right.         is not rignht

### ISSUE THREAD

**Issue by feizaihahah** [opencollab/jlatexmath#96]
**latex**: 
              \left\{ \begin{array}[1]\\2x+y=4 \\ x+2y=5 \\\end{array} \right. is not rignht
rignt:
            <img width="288" alt="image" src="https://user-images.githubusercontent.com/104407480/165210990-590ba5cb-b808-4353-844f-35437c15198d.png">

**but I use jlatexmath ，the image is** 
             <img width="348" alt="image" src="https://user-images.githubusercontent.com/104407480/165211094-5e54cb84-335a-4898-b9da-93117bb9b63b.png">

` 

public static void main(String[] args) throws IOException {
        String formula="\\left\\{ \\begin{array}[1]\\\\2x+y=4 \\\\ x+2y=5 \\\\\\end{array} \\right.";
        File directory = new File("");
        String path = directory.getCanonicalPath()+ "/latexPhotos/";
        File fileMk = new File(path);
        if (!fileMk.exists()) {
            fileMk.mkdir();
        }
        TeXFormula tf = new TeXFormula(formula);
        TeXIcon ti = tf.createTeXIcon(TeXConstants.STYLE_DISPLAY, 40);
        BufferedImage bimg = new BufferedImage(ti.getIconWidth(), ti.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g2d = bimg.createGraphics();
        Font font = g2d.getFont();
        System.out.println(font.getName());
        g2d.setColor(Color.white);
        g2d.fillRect(0,0,ti.getIconWidth(),ti.getIconHeight());
        JLabel jl = new JLabel();
        jl.setForeground(new Color(0, 0, 0));
        ti.paintIcon(jl, g2d, 0, 0);
        int hashCode =formula.hashCode();
        String fileName = System.currentTimeMillis() + "_" + hashCode + "_" + ".png";
        File file = new File(path + fileName);
        ImageIO.write(bimg, "png", file.getAbsoluteFile());
    }

`

**Comment by feizaihahah** [comment]
` public static void main(String[] args) throws IOException {
        String formula="\\left\\{ \\begin{array}[1]\\\\2x+y=4 \\\\ x+2y=5 \\\\\\end{array} \\right.";
        File directory = new File("");
        String path = directory.getCanonicalPath()+ "/latexPhotos/";
        File fileMk = new File(path);
        if (!fileMk.exists()) {
            fileMk.mkdir();
        }
        TeXFormula tf = new TeXFormula(formula);
        TeXIcon ti = tf.createTeXIcon(TeXConstants.STYLE_DISPLAY, 40);
        BufferedImage bimg = new BufferedImage(ti.getIconWidth(), ti.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g2d = bimg.createGraphics();
        Font font = g2d.getFont();
        System.out.println(font.getName());
        g2d.setColor(Color.white);
        g2d.fillRect(0,0,ti.getIconWidth(),ti.getIconHeight());
        JLabel jl = new JLabel();
        jl.setForeground(new Color(0, 0, 0));
        ti.paintIcon(jl, g2d, 0, 0);
        int hashCode =formula.hashCode();
        String fileName = System.currentTimeMillis() + "_" + hashCode + "_" + ".png";
        File file = new File(path + fileName);
        ImageIO.write(bimg, "png", file.getAbsoluteFile());
    }`

**Comment by feizaihahah** [comment]
the code is

` public static void main(String[] args) throws IOException {
        String formula="\\left\\{ \\begin{array}[1]\\\\2x+y=4 \\\\ x+2y=5 \\\\\\end{array} \\right.";
        File directory = new File("");
        String path = directory.getCanonicalPath()+ "/latexPhotos/";
        File fileMk = new File(path);
        if (!fileMk.exists()) {
            fileMk.mkdir();
        }
        TeXFormula tf = new TeXFormula(formula);
        TeXIcon ti = tf.createTeXIcon(TeXConstants.STYLE_DISPLAY, 40);
        BufferedImage bimg = new BufferedImage(ti.getIconWidth(), ti.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        Graphics2D g2d = bimg.createGraphics();
        Font font = g2d.getFont();
        System.out.println(font.getName());
        g2d.setColor(Color.white);
        g2d.fillRect(0,0,ti.getIconWidth(),ti.getIconHeight());
        JLabel jl = new JLabel();
        jl.setForeground(new Color(0, 0, 0));
        ti.paintIcon(jl, g2d, 0, 0);
        int hashCode =formula.hashCode();
        String fileName = System.currentTimeMillis() + "_" + hashCode + "_" + ".png";
        File file = new File(path + fileName);
        ImageIO.write(bimg, "png", file.getAbsoluteFile());
    }`

**Comment by murkle** [comment]
Try `[l]` not `[1]`
`{\left\{\begin{array}{l}2x+y=4 \\ x+2y=5 \\ \end{array}\right.}
`
You'll need to change each `\` to `\\` in Java
