### ISSUE TITLE
Is there a text Justify command/environment?

### ISSUE THREAD

**Issue by pablogzlezmora** [opencollab/jlatexmath#97]
Is there a Justify command/environment/trick for multiline texts (like the Justify button of MS Word: the text is aligned with both margins)? 

![20220430_051218](https://user-images.githubusercontent.com/38077825/166099564-68b3f514-c343-4e88-a76b-263e8b2df49d.png)

P.S. 
Is it suitable to ask for this kind of help with these GitHub issues?

**Comment by murkle** [comment]
Sorry, no
